library(mailR)
library(readxl)
args <- commandArgs(T)
source("/srv/myapps/keyandaydayup/email.R",encoding = "UTF-8")
taskidnow<-args[1]
app36_email<-args[2]
taskidnow<-as.character(taskidnow)
app36_email <- as.character(app36_email)
filename1<-list.files(file.path("/srv/myapps/keyandaydayup/userdata",taskidnow,"rawdata"),pattern="1",full.names=T)
outname1<-file.path("/srv/myapps/keyandaydayup/userdata",taskidnow,"result","data.fasta")
outname2<-file.path("/srv/myapps/keyandaydayup/userdata",taskidnow,"result","data.fasta.misa")
outname3<-file.path("/srv/myapps/keyandaydayup/userdata",taskidnow,"result","data.fasta")
outname4<-file.path("/srv/myapps/keyandaydayup/userdata",taskidnow,"result","result.xls")
outname5<-file.path("/srv/myapps/keyandaydayup/userdata",taskidnow,"result","misa.ini")
outname6<-file.path("/srv/myapps/keyandaydayup/userdata",taskidnow,"result")
mycmd1<-paste("/srv/myapps/keyandaydayup/scripts/app36/fasta_no_blank.pl ",filename1," > ",outname1)
mycmd2<-paste("sed -i 's/\\s/_/g' ",outname1,sep="")
mycmd3<-paste("sed -i 's/:/_/g' ",outname1,sep="")
mycmd4<-paste("cp /srv/myapps/keyandaydayup/scripts/app36/misa.ini ",outname5)
mycmd5<-paste("cd ",outname6," &&\ /srv/myapps/keyandaydayup/scripts/app36/misa.pl ",outname1)
mycmd6<-paste("cd ",outname6," &&\ /srv/myapps/keyandaydayup/scripts/app36/misa_primer3.pl ",outname2," ",outname1," 1 /srv/myapps/keyandaydayup/scripts/app36/p3_settings_file > ",outname4)
mycmd7<-paste("rm -rf ",outname6,"/misa*",sep="")
mycmd8<-paste("sed -i 's/\t\t/\t/g' ",outname4,sep="")
print(mycmd1)
print(mycmd2)
print(mycmd3)
print(mycmd4)
print(mycmd5)
print(mycmd6)
print(mycmd7)
print(mycmd8)
mycmd9<-paste(mycmd1,mycmd2,mycmd3,mycmd4,mycmd5,mycmd6,mycmd7,mycmd8,sep="&&")
print(mycmd9)
system(mycmd9)
#system(mycmd1)
#system(mycmd2)
#system(mycmd3)
#system(mycmd4)
#system(mycmd5)
#system(mycmd6)
#system(mycmd7)
#system(mycmd8)
finish<-"Job finished"
write.table(finish,file.path("/srv/myapps/keyandaydayup/userdata",taskidnow,"result","Finish.txt"),row.names=F,col.names=F,quote=F)
if(app36_email!=""&("TRUE"%in%grepl("@",app36_email))){
setwd("/srv/myapps/keyandaydayup/")
tar(file.path("userdata",taskidnow,"result.zip"),files=file.path("userdata",taskidnow,"result"))
attach.file <- file.path("/srv/myapps/keyandaydayup/userdata",taskidnow,"result.zip")
sendmail(to=as.character(app36_email),attach=T,attach.file=attach.file)
}
